version: '3.7'

services:
  kafka:
    image: jackson/kafka
    container_name: kafka
    environment:
      ADVERTISED_LISTENERS: ${ADVERTISED_LISTENERS}
    build:
      context: ./kafka
    ports:
      - 2181:2181
      - 9092:9092


